"""añadir campo is_deleted a expenses

Revision ID: 9beed7460b0d
Revises: 9bac720d5355
Create Date: 2024-11-05 14:58:24.434270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9beed7460b0d'
down_revision: Union[str, None] = '9bac720d5355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses_expenses', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('expenses_expenses', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('expenses_expenses', 'datetime',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses_expenses', 'datetime',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('expenses_expenses', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('expenses_expenses', 'is_deleted')
    # ### end Alembic commands ###
